updated version from 2015 to 2018
pengowen123/cge pull request #1
Opened 2020-09-26 08:50 UTC by MathisWellmann

using Rust version 2018 and fixed the resulting errors, no logical changes to the library just refactoring

2020-09-26 19:54 UTC, pengowen123 requested changes

2020-09-26 19:54 UTC, pengowen123 commented on README.md
> +cge = { git = "https://github.com/MathisWellmann/cge" }
This should still point to this repo.

2020-09-26 19:54 UTC, pengowen123 commented on README.md
> +- add Activation::get_func(&self) -> fn(f64) -> f64
Looks like you already added this method.

2020-09-26 19:56 UTC, pengowen123 commented
Thanks for the contribution! I noticed a few small things, but overall this looks good :+1:

2020-09-27 13:43 UTC, MathisWellmann commented
Thanks for actively looking at my PR. I'm rather new to creating pull request to other repos and originally only intended to merge the first two commits but apparently once I added more commits to my own fork it shows up here as well. regardless I kind of like all the commits as it pretty much just extends the Activation enum to more functions and provides useful methods. With the last commit I resolved your suggestions and it should hopefully be ready to merge.

2020-09-27 19:39 UTC, pengowen123 approved these changes

2020-09-27 19:39 UTC, merged